<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <LangVersion>preview</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Crowbar.TestSupport</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\UI\Crowbar.UI.csproj" />
    <ProjectReference Include="..\..\src\Engine\Engine.csproj" />
    <ProjectReference Include="..\..\src\FileSystem\Crowbar.FileSystem.csproj" />
  </ItemGroup>
</Project>
